
// This c++ code gets a pdb id from the command line, uses the pdb file and the kpcca_"id".txt file
// generated by the kpcca matlab script. The c++ code extracts a ranked list of residue pairs. The 
// main task performed here is to superimpose the kpcca matrix indices onto a protein's sequence to
// extract its real residue positions... 

// In order to run this code, Biochemical Algorithms Library (BALL) http://www.ball-project.org/ 
// and itpp http://itpp.sourceforge.net/4.3.1/ must be used.




#include <itpp/itstat.h>
#include <itpp/itbase.h>


using namespace itpp;
using namespace std;
using namespace BALL;

FragmentDB fdb("");
RotamerLibrary rl("rotamers/bbdep02.May.sortlib", fdb);

 
int main(int argc, char** argv) {
 
   std::string id = std::string(argv[1]);
   assert(id!=""); 

   ofstream logFile;
   logFile.open(("resPair_"+ id+ ".txt").c_str());   

   // read a PDB file
   PDBFile infile((id + ".pdb").c_str());
   System S;
   infile >> S;
   S.apply(fdb.normalize_names);
   S.apply(fdb.build_bonds);
   infile.close(); 
   int resNum = S.countResidues();

   
   // read in the KPCCA scores file (matrix)
   string val;
   mat cncr = zeros(resNum,resNum); 
   ifstream dataFile;
   dataFile.open(("kpcca_"+ id + ".txt").c_str());
   assert(dataFile.is_open());
   for (int i=0; i<resNum; i++) {
      for (int j=0; j<resNum; j++) {
          dataFile >> val; // cncr(i,j);
          cncr(i,j) = atof(val.c_str());
      }
   }
   dataFile.close(); 



   //extract the elements in decreasing order of KPCCA score magnitute
   double maxelmnt = 1000; int rw=-1; int cl=-1; 
   Residue * ri;
   float fii, sii;   
   ResidueRotamerSet* rsi;
   int a,b;

   itpp::max_index(cncr, rw, cl);
   maxelmnt = cncr(rw,cl);
   while ((maxelmnt>0) ) {
      cncr(rw,cl) = 0; 
      cncr(cl,rw) = 0;  
      // get real residue number of rw
      ri = S.beginProtein()->getResidue(rw);
      fii = (ri->getTorsionPhi()).toDegree();
      sii = (ri->getTorsionPsi()).toDegree();
      rsi = rl.getRotamerSet(ri->getName(), fii, sii);  
      assert(rsi); // the chosen element may not be related to a no-rotamer residue (ALA or GLY)
      istringstream(ri->getID()) >> a;
      // get real residue number of cl
      ri = S.beginProtein()->getResidue(cl);
      fii = (ri->getTorsionPhi()).toDegree();
      sii = (ri->getTorsionPsi()).toDegree();
      rsi = rl.getRotamerSet(ri->getName(), fii, sii);   
      assert(rsi); // the chosen element may not be related to a no-rotamer residue (ALA or GLY)
      istringstream(ri->getID()) >> b;
      // keep log of the residue pairs and the scores ...
      logFile << a << " " << b << " " << maxelmnt << endl;
      itpp::max_index(cncr, rw, cl);
      maxelmnt = cncr(rw,cl);
  }


  logFile.close();
  std::cout << "Done!" << std::endl;


 }
